### ISSUE TITLE
Add Lighthouse plugin

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#261]
### Acceptance criteria

We need to add the [Lighthouse plugin](https://github.com/backstage/backstage/tree/master/plugins/lighthouse). 

The EntityLastLighthouseAuditCard card should be added to  'Overview' tab in the Entity page and wrapped with the conditional `isLighthouseAvailable ` flag.

The EntityLighthouseContent card should be added to a new 'Lighthouse' tab in the Entity page (if does not exists) and wrapped with the conditional `isLighthouseAvailable ` flag.

**Comment by Zaperex** [comment]
So it appears that the lighthouse plugin linked in this issue is a frontend for the [lighthouse audit service](https://github.com/spotify/lighthouse-audit-service) and requires it to be setup beforehand.

This backend has a `startServer()` function to start the server. But this returns a `Promise<http.Server>` type which is incompatible with the createPlugin functions that are present in our example backend which seem to expect a 'Promise<express.Router>' type.

It also requires a PostgreSQL database to be setup, and I don't see any setup details for SQLite.

Any suggestions on how to proceed?

**Comment by Zaperex** [comment]
Currently this issue will be blocked by the following [bug report](https://github.com/backstage/backstage/issues/18397) for the lighthouse plugin in upstream.

**Comment by Zaperex** [comment]
The bug report fix for the lighthouse plugin in upstream has been merged and will be available in the backstage 1.16.0 release.
