### ISSUE TITLE
Update to latest Backstage 1.14

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#285]
### What needs to be done?
Run the command
`backstage-cli versions:bump`

Follow the diff from [https://backstage.github.io/upgrade-helper/?from=1.13.0&to=1.14.1](https://backstage.github.io/upgrade-helper/?from=1.13.0&to=1.14.1)

**Comment by Zaperex** [comment]
After updating the backstage version, something appears to have broken the @backstage/theme imports:
```
app:start: WARNING in ./src/App.tsx 55:61-81
app:start: export 'UnifiedThemeProvider' (imported as 'UnifiedThemeProvider') was not found in '@backstage/theme' (possible exports: colorVariants, createTheme, createThemeOptions, createThemeOverrides, darkTheme, genPageTheme, lightTheme, pageTheme, shapes)
app:start: 
app:start: WARNING in ./src/themes/janus.ts 13:26-44
app:start: export 'createUnifiedTheme' (imported as 'createUnifiedTheme') was not found in '@backstage/theme' (possible exports: colorVariants, createTheme, createThemeOptions, createThemeOverrides, darkTheme, genPageTheme, lightTheme, pageTheme, shapes)
app:start: 
app:start: webpack compiled with 2 warnings
```
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/d4c49217-2266-4ad1-844c-3286cdc475c9)
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/09d55797-c51e-4866-aaf8-85ceb03249aa)

This is weird since the docs clearly show that these 2 functions exist:
https://backstage.io/docs/reference/theme.createunifiedtheme/
https://backstage.io/docs/reference/theme.unifiedthemeprovider/

**Comment by Zaperex** [comment]
Previous issue has been resolved.
Issue was caused by `yarn backstage-cli versions:bump` downgrading the `@backstage/theme` version from `0.4.0-next.0` to `^0.3.0`
