### ISSUE TITLE
Dependabot Alerts aren't showing on Overview or tab

### ISSUE THREAD

**Issue by jayfray12** [janus-idp/backstage-showcase#347]
### What happened?
I have dependabot alerts enabled and see 4 of them in my repo however both the Overview card and the Security Insights tab do not show anything.

### What are the steps to reproduce this issue?

1. Create component (used the quarkus-web-template)
2. Enable security alerts on the repo
3. Wait for scan to complete

### Additional information

- Which devices are affected? All
- Which browsers are affected? All
- Which version are you using? sha-fb4f0f4

We only support the last 2 major versions.

Attach any related screenshots, if any.
![image (1)](https://github.com/janus-idp/backstage-showcase/assets/38667521/72f1da28-3b1e-42a9-92c6-6fecb26e2627)
![image (2)](https://github.com/janus-idp/backstage-showcase/assets/38667521/791ea2aa-d9bf-4665-aa6f-1907670d5211)
![image (3)](https://github.com/janus-idp/backstage-showcase/assets/38667521/69eb4005-6ce7-480b-bfdc-7f8cc6fd852a)

**Comment by Zaperex** [comment]
Hi @jayfray12, so I noticed that the github app needs the Repository `Dependabot Alerts` permission to be `Read-Only` at the minimum. Does your github app have that permission?
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/d9c15ac4-d398-4ede-8e2d-38b0b53db428)

I found that the dependabot alerts will not appear (and will default to all 0s) if the user is not authorized to view them.

I observed that an organization's github app can only access the dependabot alerts for the repositories inside the organization and not for any repositories outside it. 

The following is the alert for a quarkus-demo repository inside the organization
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/ef2e317c-5a9d-48f8-9a2f-3b12912264fc)

This is the alert for a repository outside the organization (owned by the owner of the organization)
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/48714a2c-90f0-4f43-832b-6e67b252359a)

The same thing happens if you try to access the organization's repositories with a personal github app (even if you're the owner of the organization). 

The following is the alert for the same quarkus-demo repository inside the organization, but accessed using a personal token.
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/02012bb7-bbe6-4f89-b840-3a80d627fc0d)

This is the alert for the same repository outside the organization
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/e164c081-d51d-4948-b524-c611223e1af4)

You will also not be able to have the dependabot alerts appear if the account you try to login with doesn't have access to the dependabot alerts for the repository.

**Comment by jayfray12** [comment]
I probably have something configured incorrectly.  Is there documentation on how to set this up?  My app-config looks similar to this:
![image](https://github.com/janus-idp/backstage-showcase/assets/38667521/af49e74b-b83c-469e-9911-fb77403ff159)

And this is what the App looks like in Git.  So it has the read permission and is setup inside the org
![image](https://github.com/janus-idp/backstage-showcase/assets/38667521/6650952e-e4fa-4cf5-b4fe-e024ff6b069d)

So I would assume based on what you stated it should work but it still is showing zeros.  (I can click the "More Info" and it takes me right to the dependabot page, not getting a 404, which shows there are 13 alerts

**Comment by Zaperex** [comment]
@jayfray12 can I ask if you have `auth` setup? You might need to be authenticated via github for the plugin to load?
```yaml
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_APP_CLIENT_ID}
        clientSecret: ${GITHUB_APP_CLIENT_SECRET}
```

**Comment by jayfray12** [comment]
That was it!  I had a different (OAuth App) clientId/clientSecret set for the auth setup than the integration and that OAuth App was not part of the Organization.  Once I switched the auth setup to use the same clientId/clientSecret as the App setup in the org it worked.   Thanks for the help @Zaperex 

Perhaps documentation around this would have prevented the confusion :smile:

**Comment by Zaperex** [comment]
Main question would be where to include this documentation, since this isn't a plugin we are maintaining. The plugin maintainer's [documentation](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-security-insights) doesn't mention any of the prerequisites that the plugin would require. Maybe I could update the requirements/caveats there.
