### ISSUE TITLE
Add devtools-backend plugin

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#480]
### What do you want to improve?

We need to add the devtools-backend plugin:
https://github.com/backstage/backstage/blob/53b916f7a8f788893e42c4aa61f66b4628b54850/plugins/devtools-backend/README.md

**Comment by Zaperex** [comment]
Would we also want the corresponding [devtools-frontend plugin](https://github.com/backstage/backstage/blob/53b916f7a8f788893e42c4aa61f66b4628b54850/plugins/devtools/README.md) to be installed as well? Since it seems the backend only provides data for the frontend, just installing it on its own won't make the data visible to the end users.

**Comment by Zaperex** [comment]
Previous PR closed since we now want to install this dynamically.

**Comment by Zaperex** [comment]
@kadel @christophe-f are we still planning this for GA? If so, I'll quickly work on setting up a dynamic wrapper for the devtools frontend and backend.

**Comment by christophe-f** [comment]
It can be done after GA. Also with dynamic plugins we probably don't need to do that anymore.
