### ISSUE TITLE
Optimize Dockerfile performance

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#55]
### What do you want to improve?

Optimize Dockerfile to run faster. We have many contributions and it takes a long time to get feedback, merge and deploy.

### What is the current behavior?

The build time was already too long and doubled in the last week. 

### What is the new behavior?

Build faster. Much faster

### :warning: Is this a breaking change?

_Put an `x` in the boxes that apply_

- [ ] Yes
- [x] No
- [ ] Don't know

**Comment by schultzp2020** [comment]
Currently, the majority of the dockerfile build time is allocated to running the [`fix-permissions`](https://github.com/janus-idp/backstage-showcase/blob/main/Dockerfile#L75) script. Is there a way we could cut down the time required to run this script? @sabre1041 @tumido

**Comment by tumido** [comment]
@schultzp2020 I think you can make the Dockerfile to use the `fix-permissions` script earlier in multiple layers instead of just as the last one. What that would result into is incremental changes - container layers work in a way that they store all that is changed compared to the previous layer. So, if the `fix-permissions` was already executed for some files, it means the permissions don't have to be updated for them again + these files are already cached in their final state in previous layers. This should potentially (and counterintuitively) result in smaller and faster builds.

**Comment by Zaperex** [comment]
End users will no longer be building their own backstage showcase images, so this issue is mainly for improving our own build times for showcase and RHDH.

Currently I have only identified optimizations for the first stage (dependency installations) by only copying `package.json` files.

**Comment by Zaperex** [comment]
It appears the upstream has updated the documentation regarding Dockerfiles for this issue.
https://github.com/backstage/backstage/pull/18612#discussion_r1257392564

**Comment by schultzp2020** [comment]
There are no optimizations we can do for the dockerfile since the `fix-permissions` script takes the most amount of time and we do not control the script.
