### ISSUE TITLE
Test SAML integration

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#645]
### What needs to be done?
Test that Showcase is working with SAML

https://github.com/backstage/backstage/blob/b1f4c99f79f2640ae3f12139923850c47f61aa4c/plugins/auth-backend/scripts/start-saml-idp.sh

**Comment by Zaperex** [comment]
Currently SAML is not supported in the showcase because the showcase does not have the [SAML auth provider](https://github.com/backstage/backstage/blob/b1f4c99f79f2640ae3f12139923850c47f61aa4c/plugins/auth-backend/src/providers/saml/provider.ts) setup.
https://backstage.io/docs/reference/plugin-auth-backend.providers/
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/8dbe20f5-5774-4f08-8cab-777a4baaed01)

We also currently don't have a specific sign-in page for SAML yet, which would require a custom apiRef and sign-in configuration like the following:
```ts
{
  id: 'saml-auth-provider',
  title: 'SAML',
  message: 'Sign in using SAML',
  apiRef: samlAuthApiRef,
},
```
```ts
export const samlAuthApiRef: ApiRef<
  OAuthApi &
    OpenIdConnectApi &
    ProfileInfoApi &
    BackstageIdentityApi &
    SessionApi
> = createApiRef({
  id: 'internal.auth.saml',
});
```
Then we would register the API similar to how @schultzp2020 registered the OIDC apiRef in https://github.com/janus-idp/backstage-showcase/pull/602 in [`packages/app/src/api/AuthApiRefs.ts`](https://github.com/janus-idp/backstage-showcase/blob/faaca32e0d1abf6da5b2a348a2f12c25e32f4a46/packages/app/src/api/AuthApiRefs.ts)
```ts
// SAML
export const apis: AnyApiFactory[] = [
  ...
  createApiFactory({
    api: samlAuthApiRef,
    deps: {
      discoveryApi: discoveryApiRef,
      oauthRequestApi: oauthRequestApiRef,
      configApi: configApiRef,
    },
    factory: ({ discoveryApi, oauthRequestApi, configApi }) =>
      OAuth2.create({
	discoveryApi,
	oauthRequestApi,
	provider: {
	  id: 'saml',
	  title: 'SAML',
	  icon: () => null,
	},
	environment: configApi.getOptionalString('auth.environment'),
      }),
  }),
];
```
Then the users would need to also configure the `saml` provider in the `auth.providers` section of the `app-config.yaml` according to the [schema specified by the `config.d.ts`](https://github.com/backstage/backstage/blob/b1f4c99f79f2640ae3f12139923850c47f61aa4c/plugins/auth-backend/config.d.ts#L99-L121) which currently doesn't have much documentation on what's expected as inputs.

**Comment by schultzp2020** [comment]
@christophe-f @Zaperex I will add `saml` support in https://github.com/janus-idp/backstage-showcase/pull/602.

**Comment by Zaperex** [comment]
Blocked by #602 and #588

**Comment by Zaperex** [comment]
Verified and the SAML sign-in works as expected.
